// <auto-generated />
using ExpensesTracker.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpensesTracker.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220925155454_firstMig")]
    partial class firstMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("ExpensesTracker.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Groceries"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Transportation"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Health"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Entertainment"
                        });
                });

            modelBuilder.Entity("ExpensesTracker.Shared.MonthlyExp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Money")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MonthlyExps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Comment = "Chicken has become quite expensive",
                            Money = 435.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Comment = "Buses are slow",
                            Money = 25.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Comment = "partyyy",
                            Money = 1000.0
                        });
                });

            modelBuilder.Entity("ExpensesTracker.Shared.MonthlyExp", b =>
                {
                    b.HasOne("ExpensesTracker.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
